### ISSUE TITLE
Oh no. Error running app.

### ISSUE THREAD

**Issue by bordeauxred** [Consistent-Hparams/Website#1]
When trying to access the [webpage](https://consistent-hyperparameters.streamlit.app/), I keep getting the message:
"Oh no. Error running app. If this keeps happening, please contact support",
across safari, chrome and brave.

**Comment by Consistent-Hparams** [comment]
Hi!
Try https://consistent-hparams.streamlit.app/, which is the URL in our
paper (I messed up the URLs in the last few days)

Best,

João

**Comment by bordeauxred** [comment]
This works, thank you very much, João!
